# This is a basic workflow to help you get started with Actions

name: DEPLOYMENT

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ master ]
  schedule:
    - cron:  '30 3 * * *' # everyday at 03:30

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: uberspace_hosting
    steps:
      - name: Update and Build
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: |
            set -e
            cd ${{ secrets.DEPLOYMENT_ROOT }}
            git clone --depth 1 https://github.com/rhein-main-swingtime/event-notification-symfony-php.git event_notification_${{ github.run_number }}_${{ github.sha }}
            cd event_notification_${{ github.run_number }}_${{ github.sha }}
            printf "${{ secrets.PROD_DECRYPT_PRIVATE }}" > config/secrets/prod/prod.decrypt.private.php
            sed -i 's/dev/prod/' .env
            /bin/cp -rf helpers/reset_opcache.php public
            composer --no-dev install

      - name: Linking
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: |
            set -e
            cd ${{ secrets.DEPLOYMENT_ROOT }}

            # ## Linking
            if [ -e  "${{ secrets.DEPLOYMENT_ROOT }}/event_notification/bin" ]; then
              rm -f ${{ secrets.DEPLOYMENT_ROOT }}/event_notification/bin
            fi
            ln -s ${{ secrets.DEPLOYMENT_ROOT }}/event_notification_${{ github.run_number }}_${{ github.sha }}/bin ${{ secrets.DEPLOYMENT_ROOT }}/event_notification/bin

            if [ -d "${{ secrets.DEPLOYMENT_ROOT }}/event_notification_${{ github.run_number }}_${{ github.sha }}/var/log" ]; then
              rm -r ${{ secrets.DEPLOYMENT_ROOT }}/event_notification_${{ github.run_number }}_${{ github.sha }}/var/log
            fi
            ln -s ${{ secrets.DEPLOYMENT_ROOT }}/event_notification/log ${{ secrets.DEPLOYMENT_ROOT }}/event_notification_${{ github.run_number }}_${{ github.sha }}/var/log

            ## Public link
            rm ${{ secrets.FQDN }}
            ln -s event_notification_${{ github.run_number }}_${{ github.sha }}/public ${{ secrets.FQDN }}

            ## Cache reset
            curl -H 'Cache-Control: no-cache, no-store' https://${{ secrets.FQDN }}/reset_opcache.php
            rm ${{ secrets.FQDN }}/reset_opcache.php

            ## Cleanup
            echo "Deleting old builds (keeping 10)"
            ls -tp | grep event_notification_ | grep -v '\$' | tail -n +10 | xargs -d '\n' -r rm -r --