# This is a basic workflow to help you get started with Actions

name: DEPLOYMENT

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ master ]
  schedule:
    - cron:  '30 3 * * *' # everyday at 03:30

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: uberspace_hosting
    steps:
      - name: Update and Build
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: |
            cd ${{ secrets.DEPLOYMENT_ROOT }}
            git clone --depth 1 https://github.com/rhein-main-swingtime/event-notification-symfony-php.git event_notification_${{ github.run_number }}_${{ github.sha }}
            cd event_notification_${{ github.run_number }}_${{ github.sha }}
            printf "${{ secrets.PROD_DECRYPT_PRIVATE }}" > config/secrets/prod/prod.decrypt.private.php
            sed -i 's/dev/prod/' .env
            composer install
            cp helpers/reset_opcache.php public
            curl https://${{ secrets.FQDN }}/reset_opcache.php
            rm public/reset_opcache.php

      - name: Linking
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: |
            cd ${{ secrets.DEPLOYMENT_ROOT }}
            rm ${{ secrets.FQDN }}
            ln -s event_notification_${{ github.run_number }}_${{ github.sha }}/public ${{ secrets.FQDN }}
            echo "Deleting old builds (keeping 10)"
            ls -tp | event_notification_ | grep -v '\$' | tail -n +10 | xargs -d '\n' -r rm -r --