# This is a basic workflow to help you get started with Actions

name: POST UPDATES

# Controls when the action will run.
on:
  schedule:
    - cron:  '30 8 * * *' # everyday at 08:30

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: uberspace_hosting
    steps:
      - name: Fetch
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: |
            set -e
            curl --verbose "https://${{ secrets.FQDN }}/post-updates?auth=${{ secrets.POST_UPDATES_AUTH }}"