# This is a basic workflow to help you get started with Actions

name: POST UPDATES

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ master ]
  schedule:
    - cron:  '30 3 * * *' # everyday at 03:30

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: uberspace_hosting
    steps:
      - name: Update and Build
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: |
            curl --verbose "https://${{ secrets.FQDN }}/post-updates?auth=${{ secrets.POST_UPDATES_AUTH }}"